import type { LandingLocaleCode } from '../i18n';

export interface PricingCampaignContent {
  badge: string;
  headline: string;
  body: string;
  windowLabel: string;
  dayUnit: string;
  modelBenefit: string;
  paidBenefitNote: string;
  teamBenefitNote: string;
  disclaimer: string;
}

export const PRICING_CAMPAIGN_CONTENT_BY_LOCALE = {
  en: {
    badge: 'Unlimited',
    headline: 'This time, top-tier intelligence is wide open.',
    body: 'DeepSeek V4 Pro and V4 Flash · two weeks free',
    windowLabel: 'Campaign countdown',
    dayUnit: 'd',
    modelBenefit: 'DeepSeek V4 Pro and V4 Flash free for two weeks',
    paidBenefitNote: 'DeepSeek V4 Pro and V4 Flash · two weeks free',
    teamBenefitNote: 'DeepSeek V4 Pro and V4 Flash · two weeks free',
    disclaimer: 'Unlimited model quota and free generations included in a plan are available only in open design, not through MCP, CLI, API, or other scenarios.',
  },
  zh: {
    badge: '无限使用',
    headline: '这次，顶级智能放开用。',
    body: 'DeepSeek V4 Pro 与 V4 Flash · 两周免费用',
    windowLabel: '活动倒计时',
    dayUnit: '天',
    modelBenefit: 'DeepSeek V4 Pro 与 V4 Flash 两周免费',
    paidBenefitNote: 'DeepSeek V4 Pro 与 V4 Flash · 两周免费用',
    teamBenefitNote: 'DeepSeek V4 Pro 与 V4 Flash · 两周免费用',
    disclaimer: '套餐内的无限制模型额度与免费生成次数，仅可通过Open Design使用；无法在MCP/CLI/API及其他场景使用。解释权归官方所有。',
  },
  ja: {
    badge: '無制限',
    headline: '今回は、最上位の知能を思いきり使おう。',
    body: 'DeepSeek V4 Pro と V4 Flash · 2週間無料',
    windowLabel: 'キャンペーン終了まで',
    dayUnit: '日',
    modelBenefit: 'DeepSeek V4 Pro と V4 Flash が2週間無料',
    paidBenefitNote: 'DeepSeek V4 Pro と V4 Flash · 2週間無料',
    teamBenefitNote: 'DeepSeek V4 Pro と V4 Flash · 2週間無料',
    disclaimer: 'プランに含まれる無制限のモデル枠と無料生成回数は、Open Design内でのみ利用できます。MCP/CLI/APIなど、その他の環境では利用できません。最終的な解釈権は運営者に帰属します。',
  },
  ko: {
    badge: '무제한 사용',
    headline: '이번에는 최상위 지능을 마음껏 쓰세요.',
    body: 'DeepSeek V4 Pro와 V4 Flash · 2주 무료',
    windowLabel: '이벤트 남은 시간',
    dayUnit: '일',
    modelBenefit: 'DeepSeek V4 Pro와 V4 Flash 2주 무료',
    paidBenefitNote: 'DeepSeek V4 Pro와 V4 Flash · 2주 무료',
    teamBenefitNote: 'DeepSeek V4 Pro와 V4 Flash · 2주 무료',
    disclaimer: '플랜에 포함된 무제한 모델 한도와 무료 생성 횟수는 Open Design에서만 사용할 수 있으며 MCP/CLI/API 또는 기타 환경에서는 사용할 수 없습니다. 최종 해석 권한은 운영사에 있습니다.',
  },
  de: {
    badge: 'Unbegrenzt',
    headline: 'Diesmal ist Top-Intelligenz weit geöffnet.',
    body: 'DeepSeek V4 Pro und V4 Flash · zwei Wochen kostenlos',
    windowLabel: 'Aktions-Countdown',
    dayUnit: 'T',
    modelBenefit: 'DeepSeek V4 Pro und V4 Flash zwei Wochen kostenlos',
    paidBenefitNote: 'DeepSeek V4 Pro und V4 Flash · zwei Wochen kostenlos',
    teamBenefitNote: 'DeepSeek V4 Pro und V4 Flash · zwei Wochen kostenlos',
    disclaimer: 'Das im Tarif enthaltene unbegrenzte Modellkontingent und die kostenlosen Generierungen können nur in Open Design genutzt werden, nicht über MCP/CLI/API oder in anderen Umgebungen. Der Veranstalter behält sich die endgültige Auslegung vor.',
  },
  fr: {
    badge: 'Illimité',
    headline: 'Cette fois, l’intelligence haut de gamme est grande ouverte.',
    body: 'DeepSeek V4 Pro et V4 Flash · deux semaines gratuites',
    windowLabel: 'Compte à rebours',
    dayUnit: 'j',
    modelBenefit: 'DeepSeek V4 Pro et V4 Flash gratuits pendant deux semaines',
    paidBenefitNote: 'DeepSeek V4 Pro et V4 Flash · deux semaines gratuites',
    teamBenefitNote: 'DeepSeek V4 Pro et V4 Flash · deux semaines gratuites',
    disclaimer: 'Le quota de modèles illimité et les générations gratuites inclus dans le forfait sont utilisables uniquement dans Open Design, et non via MCP/CLI/API ni dans d’autres contextes. L’organisateur se réserve le droit d’interprétation finale.',
  },
  ru: {
    badge: 'Без ограничений',
    headline: 'На этот раз топовый интеллект полностью открыт.',
    body: 'DeepSeek V4 Pro и V4 Flash · две недели бесплатно',
    windowLabel: 'До конца акции',
    dayUnit: 'д',
    modelBenefit: 'DeepSeek V4 Pro и V4 Flash две недели бесплатно',
    paidBenefitNote: 'DeepSeek V4 Pro и V4 Flash · две недели бесплатно',
    teamBenefitNote: 'DeepSeek V4 Pro и V4 Flash · две недели бесплатно',
    disclaimer: 'Безлимитная квота моделей и бесплатные генерации, включённые в тариф, доступны только в Open Design и недоступны через MCP/CLI/API или в других сценариях. Организатор оставляет за собой право окончательного толкования.',
  },
  es: {
    badge: 'Uso ilimitado',
    headline: 'Esta vez, la inteligencia de primer nivel está abierta.',
    body: 'DeepSeek V4 Pro y V4 Flash · dos semanas gratis',
    windowLabel: 'Cuenta atrás de la promoción',
    dayUnit: 'd',
    modelBenefit: 'DeepSeek V4 Pro y V4 Flash gratis durante dos semanas',
    paidBenefitNote: 'DeepSeek V4 Pro y V4 Flash · dos semanas gratis',
    teamBenefitNote: 'DeepSeek V4 Pro y V4 Flash · dos semanas gratis',
    disclaimer: 'La cuota ilimitada de modelos y las generaciones gratuitas incluidas en el plan solo pueden utilizarse en Open Design, no mediante MCP/CLI/API ni en otros entornos. El organizador se reserva el derecho de interpretación final.',
  },
  'pt-br': {
    badge: 'Uso ilimitado',
    headline: 'Desta vez, a inteligência de ponta está liberada.',
    body: 'DeepSeek V4 Pro e V4 Flash · duas semanas grátis',
    windowLabel: 'Contagem regressiva',
    dayUnit: 'd',
    modelBenefit: 'DeepSeek V4 Pro e V4 Flash grátis por duas semanas',
    paidBenefitNote: 'DeepSeek V4 Pro e V4 Flash · duas semanas grátis',
    teamBenefitNote: 'DeepSeek V4 Pro e V4 Flash · duas semanas grátis',
    disclaimer: 'A cota ilimitada de modelos e as gerações gratuitas incluídas no plano só podem ser usadas no Open Design, e não via MCP/CLI/API nem em outros cenários. O organizador se reserva o direito de interpretação final.',
  },
  it: {
    badge: 'Uso illimitato',
    headline: 'Questa volta l’intelligenza di primo livello è aperta.',
    body: 'DeepSeek V4 Pro e V4 Flash · due settimane gratis',
    windowLabel: 'Conto alla rovescia',
    dayUnit: 'g',
    modelBenefit: 'DeepSeek V4 Pro e V4 Flash gratis per due settimane',
    paidBenefitNote: 'DeepSeek V4 Pro e V4 Flash · due settimane gratis',
    teamBenefitNote: 'DeepSeek V4 Pro e V4 Flash · due settimane gratis',
    disclaimer: 'La quota modelli illimitata e le generazioni gratuite incluse nel piano sono utilizzabili solo in Open Design, non tramite MCP/CLI/API né in altri contesti. L’organizzatore si riserva il diritto di interpretazione finale.',
  },
  tr: {
    badge: 'Sınırsız kullanım',
    headline: 'Bu sefer üst düzey zeka sonuna kadar açık.',
    body: 'DeepSeek V4 Pro ve V4 Flash · iki hafta ücretsiz',
    windowLabel: 'Kampanya geri sayımı',
    dayUnit: 'g',
    modelBenefit: 'DeepSeek V4 Pro ve V4 Flash iki hafta ücretsiz',
    paidBenefitNote: 'DeepSeek V4 Pro ve V4 Flash · iki hafta ücretsiz',
    teamBenefitNote: 'DeepSeek V4 Pro ve V4 Flash · iki hafta ücretsiz',
    disclaimer: 'Paket kapsamındaki sınırsız model kotası ve ücretsiz üretim hakları yalnızca Open Design içinde kullanılabilir; MCP/CLI/API veya diğer senaryolarda kullanılamaz. Nihai yorum hakkı organizatöre aittir.',
  },
  'zh-tw': {
    badge: '無限使用',
    headline: '這次，頂級智能放開用。',
    body: 'DeepSeek V4 Pro 與 V4 Flash · 兩週免費用',
    windowLabel: '活動倒計時',
    dayUnit: '天',
    modelBenefit: 'DeepSeek V4 Pro 與 V4 Flash 兩週免費',
    paidBenefitNote: 'DeepSeek V4 Pro 與 V4 Flash · 兩週免費用',
    teamBenefitNote: 'DeepSeek V4 Pro 與 V4 Flash · 兩週免費用',
    disclaimer: '套餐內的無限制模型額度與免費生成次數，僅可透過Open Design使用；無法在MCP/CLI/API及其他場景使用。解釋權歸官方所有。',
  },
  vi: {
    badge: 'Không giới hạn',
    headline: 'Lần này, trí tuệ hàng đầu được mở rộng.',
    body: 'DeepSeek V4 Pro và V4 Flash · miễn phí hai tuần',
    windowLabel: 'Đếm ngược chiến dịch',
    dayUnit: 'n',
    modelBenefit: 'DeepSeek V4 Pro và V4 Flash miễn phí hai tuần',
    paidBenefitNote: 'DeepSeek V4 Pro và V4 Flash · miễn phí hai tuần',
    teamBenefitNote: 'DeepSeek V4 Pro và V4 Flash · miễn phí hai tuần',
    disclaimer: 'Hạn mức mô hình không giới hạn và lượt tạo miễn phí trong gói chỉ dùng được trong Open Design, không qua MCP/CLI/API hay ngữ cảnh khác. Quyền giải thích cuối cùng thuộc về ban tổ chức.',
  },
  pl: {
    badge: 'Bez limitu',
    headline: 'Tym razem najwyższa inteligencja jest szeroko otwarta.',
    body: 'DeepSeek V4 Pro i V4 Flash · dwa tygodnie za darmo',
    windowLabel: 'Odliczanie kampanii',
    dayUnit: 'd',
    modelBenefit: 'DeepSeek V4 Pro i V4 Flash za darmo przez dwa tygodnie',
    paidBenefitNote: 'DeepSeek V4 Pro i V4 Flash · dwa tygodnie za darmo',
    teamBenefitNote: 'DeepSeek V4 Pro i V4 Flash · dwa tygodnie za darmo',
    disclaimer: 'Nieograniczony limit modeli i darmowe generacje w planie działają tylko w Open Design, nie przez MCP/CLI/API ani w innych scenariuszach. Organizator zastrzega sobie prawo ostatecznej interpretacji.',
  },
  id: {
    badge: 'Tanpa batas',
    headline: 'Kali ini, kecerdasan kelas atas dibuka lebar.',
    body: 'DeepSeek V4 Pro dan V4 Flash · dua minggu gratis',
    windowLabel: 'Hitung mundur kampanye',
    dayUnit: 'h',
    modelBenefit: 'DeepSeek V4 Pro dan V4 Flash gratis dua minggu',
    paidBenefitNote: 'DeepSeek V4 Pro dan V4 Flash · dua minggu gratis',
    teamBenefitNote: 'DeepSeek V4 Pro dan V4 Flash · dua minggu gratis',
    disclaimer: 'Kuota model tanpa batas dan generasi gratis dalam paket hanya dapat digunakan di Open Design, bukan melalui MCP/CLI/API atau skenario lain. Penyelenggara berhak atas interpretasi akhir.',
  },
  nl: {
    badge: 'Onbeperkt',
    headline: 'Deze keer staat topintelligentie wijd open.',
    body: 'DeepSeek V4 Pro en V4 Flash · twee weken gratis',
    windowLabel: 'Campagne-aftelling',
    dayUnit: 'd',
    modelBenefit: 'DeepSeek V4 Pro en V4 Flash twee weken gratis',
    paidBenefitNote: 'DeepSeek V4 Pro en V4 Flash · twee weken gratis',
    teamBenefitNote: 'DeepSeek V4 Pro en V4 Flash · twee weken gratis',
    disclaimer: 'Het onbeperkte modelquotum en de gratis generaties in je plan zijn alleen beschikbaar in Open Design, niet via MCP/CLI/API of andere scenario’s. De organisator behoudt het recht op definitieve interpretatie.',
  },
  ar: {
    badge: 'بلا حدود',
    headline: 'هذه المرة، الذكاء من الدرجة الأولى مفتوح على مصراعيه.',
    body: 'DeepSeek V4 Pro و V4 Flash · أسبوعان مجانًا',
    windowLabel: 'العد التنازلي للحملة',
    dayUnit: 'ي',
    modelBenefit: 'DeepSeek V4 Pro و V4 Flash مجانًا لأسبوعين',
    paidBenefitNote: 'DeepSeek V4 Pro و V4 Flash · أسبوعان مجانًا',
    teamBenefitNote: 'DeepSeek V4 Pro و V4 Flash · أسبوعان مجانًا',
    disclaimer: 'حصة النماذج غير المحدودة ومرات التوليد المجانية ضمن الخطة متاحة فقط داخل Open Design، وليس عبر MCP/CLI/API أو سيناريوهات أخرى. حق التفسير النهائي للجهة المنظمة.',
  },
  uk: {
    badge: 'Без обмежень',
    headline: 'Цього разу топовий інтелект повністю відкритий.',
    body: 'DeepSeek V4 Pro і V4 Flash · два тижні безкоштовно',
    windowLabel: 'Відлік кампанії',
    dayUnit: 'д',
    modelBenefit: 'DeepSeek V4 Pro і V4 Flash два тижні безкоштовно',
    paidBenefitNote: 'DeepSeek V4 Pro і V4 Flash · два тижні безкоштовно',
    teamBenefitNote: 'DeepSeek V4 Pro і V4 Flash · два тижні безкоштовно',
    disclaimer: 'Безлімітна квота моделей і безкоштовні генерації в тарифі доступні лише в Open Design, а не через MCP/CLI/API чи в інших сценаріях. Організатор залишає за собою право остаточного тлумачення.',
  },
} satisfies Partial<Record<LandingLocaleCode, PricingCampaignContent>>;

export function getPricingCampaignContent(
  locale: LandingLocaleCode,
): PricingCampaignContent {
  return PRICING_CAMPAIGN_CONTENT_BY_LOCALE[locale as keyof typeof PRICING_CAMPAIGN_CONTENT_BY_LOCALE]
    ?? PRICING_CAMPAIGN_CONTENT_BY_LOCALE.en;
}
